import type { Metadata } from "next";
import { EB_Garamond} from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/nav_bar";

const ebGaramond = EB_Garamond({
  variable: "--font-eb-garamond",
  subsets: ["latin"]
})

const hack = localFont({
  src: "../public/fonts/hack/Hack-Regular.ttf",
  variable: "--font-hack"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ebGaramond.variable} ${hack.variable} antialiased`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}


